version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errname
    - errorlint
    - gocritic
    - godot
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
